import { GameRankConfig } from '../types';

export const DOTA2_RANKS: GameRankConfig = {
  gameCode: 'DOTA2',
  gameName: 'Dota 2',
  rankLabel: 'MMR',
  currency: 'USD',
  pricePerStep: 4.99,
  ranks: [
    { id: 'dota2_herald1',   name: 'Herald I',    tier: 'Herald',   division: 1, order: 0 },
    { id: 'dota2_herald2',   name: 'Herald II',   tier: 'Herald',   division: 2, order: 1 },
    { id: 'dota2_herald3',   name: 'Herald III',  tier: 'Herald',   division: 3, order: 2 },
    { id: 'dota2_herald4',   name: 'Herald IV',   tier: 'Herald',   division: 4, order: 3 },
    { id: 'dota2_herald5',   name: 'Herald V',    tier: 'Herald',   division: 5, order: 4 },
    { id: 'dota2_guardian1', name: 'Guardian I',   tier: 'Guardian', division: 1, order: 5 },
    { id: 'dota2_guardian2', name: 'Guardian II',  tier: 'Guardian', division: 2, order: 6 },
    { id: 'dota2_guardian3', name: 'Guardian III', tier: 'Guardian', division: 3, order: 7 },
    { id: 'dota2_guardian4', name: 'Guardian IV',  tier: 'Guardian', division: 4, order: 8 },
    { id: 'dota2_guardian5', name: 'Guardian V',   tier: 'Guardian', division: 5, order: 9 },
    { id: 'dota2_crusader1', name: 'Crusader I',   tier: 'Crusader', division: 1, order: 10 },
    { id: 'dota2_crusader2', name: 'Crusader II',  tier: 'Crusader', division: 2, order: 11 },
    { id: 'dota2_crusader3', name: 'Crusader III', tier: 'Crusader', division: 3, order: 12 },
    { id: 'dota2_crusader4', name: 'Crusader IV',  tier: 'Crusader', division: 4, order: 13 },
    { id: 'dota2_crusader5', name: 'Crusader V',   tier: 'Crusader', division: 5, order: 14 },
    { id: 'dota2_archon1',  name: 'Archon I',     tier: 'Archon',   division: 1, order: 15 },
    { id: 'dota2_archon2',  name: 'Archon II',    tier: 'Archon',   division: 2, order: 16 },
    { id: 'dota2_archon3',  name: 'Archon III',   tier: 'Archon',   division: 3, order: 17 },
    { id: 'dota2_archon4',  name: 'Archon IV',    tier: 'Archon',   division: 4, order: 18 },
    { id: 'dota2_archon5',  name: 'Archon V',     tier: 'Archon',   division: 5, order: 19 },
    { id: 'dota2_legend1',  name: 'Legend I',      tier: 'Legend',   division: 1, order: 20 },
    { id: 'dota2_legend2',  name: 'Legend II',     tier: 'Legend',   division: 2, order: 21 },
    { id: 'dota2_legend3',  name: 'Legend III',    tier: 'Legend',   division: 3, order: 22 },
    { id: 'dota2_legend4',  name: 'Legend IV',     tier: 'Legend',   division: 4, order: 23 },
    { id: 'dota2_legend5',  name: 'Legend V',      tier: 'Legend',   division: 5, order: 24 },
    { id: 'dota2_ancient1', name: 'Ancient I',     tier: 'Ancient',  division: 1, order: 25 },
    { id: 'dota2_ancient2', name: 'Ancient II',    tier: 'Ancient',  division: 2, order: 26 },
    { id: 'dota2_ancient3', name: 'Ancient III',   tier: 'Ancient',  division: 3, order: 27 },
    { id: 'dota2_ancient4', name: 'Ancient IV',    tier: 'Ancient',  division: 4, order: 28 },
    { id: 'dota2_ancient5', name: 'Ancient V',     tier: 'Ancient',  division: 5, order: 29 },
    { id: 'dota2_divine1',  name: 'Divine I',      tier: 'Divine',   division: 1, order: 30 },
    { id: 'dota2_divine2',  name: 'Divine II',     tier: 'Divine',   division: 2, order: 31 },
    { id: 'dota2_divine3',  name: 'Divine III',    tier: 'Divine',   division: 3, order: 32 },
    { id: 'dota2_divine4',  name: 'Divine IV',     tier: 'Divine',   division: 4, order: 33 },
    { id: 'dota2_divine5',  name: 'Divine V',      tier: 'Divine',   division: 5, order: 34 },
    { id: 'dota2_immortal', name: 'Immortal',      tier: 'Immortal',             order: 35 },
  ],
};
