import { GameRankConfig } from '../types';

export const LOL_RANKS: GameRankConfig = {
  gameCode: 'LOL',
  gameName: 'League of Legends',
  rankLabel: 'Rank',
  currency: 'USD',
  pricePerStep: 4.99,
  ranks: [
    { id: 'lol_iron4',    name: 'Iron IV',    tier: 'Iron',    division: 4, order: 0 },
    { id: 'lol_iron3',    name: 'Iron III',   tier: 'Iron',    division: 3, order: 1 },
    { id: 'lol_iron2',    name: 'Iron II',    tier: 'Iron',    division: 2, order: 2 },
    { id: 'lol_iron1',    name: 'Iron I',     tier: 'Iron',    division: 1, order: 3 },
    { id: 'lol_bronze4',  name: 'Bronze IV',  tier: 'Bronze',  division: 4, order: 4 },
    { id: 'lol_bronze3',  name: 'Bronze III', tier: 'Bronze',  division: 3, order: 5 },
    { id: 'lol_bronze2',  name: 'Bronze II',  tier: 'Bronze',  division: 2, order: 6 },
    { id: 'lol_bronze1',  name: 'Bronze I',   tier: 'Bronze',  division: 1, order: 7 },
    { id: 'lol_silver4',  name: 'Silver IV',  tier: 'Silver',  division: 4, order: 8 },
    { id: 'lol_silver3',  name: 'Silver III', tier: 'Silver',  division: 3, order: 9 },
    { id: 'lol_silver2',  name: 'Silver II',  tier: 'Silver',  division: 2, order: 10 },
    { id: 'lol_silver1',  name: 'Silver I',   tier: 'Silver',  division: 1, order: 11 },
    { id: 'lol_gold4',    name: 'Gold IV',    tier: 'Gold',    division: 4, order: 12 },
    { id: 'lol_gold3',    name: 'Gold III',   tier: 'Gold',    division: 3, order: 13 },
    { id: 'lol_gold2',    name: 'Gold II',    tier: 'Gold',    division: 2, order: 14 },
    { id: 'lol_gold1',    name: 'Gold I',     tier: 'Gold',    division: 1, order: 15 },
    { id: 'lol_plat4',    name: 'Platinum IV',  tier: 'Platinum',  division: 4, order: 16 },
    { id: 'lol_plat3',    name: 'Platinum III', tier: 'Platinum',  division: 3, order: 17 },
    { id: 'lol_plat2',    name: 'Platinum II',  tier: 'Platinum',  division: 2, order: 18 },
    { id: 'lol_plat1',    name: 'Platinum I',   tier: 'Platinum',  division: 1, order: 19 },
    { id: 'lol_emerald4', name: 'Emerald IV',   tier: 'Emerald',   division: 4, order: 20 },
    { id: 'lol_emerald3', name: 'Emerald III',  tier: 'Emerald',   division: 3, order: 21 },
    { id: 'lol_emerald2', name: 'Emerald II',   tier: 'Emerald',   division: 2, order: 22 },
    { id: 'lol_emerald1', name: 'Emerald I',    tier: 'Emerald',   division: 1, order: 23 },
    { id: 'lol_diamond4', name: 'Diamond IV',   tier: 'Diamond',   division: 4, order: 24 },
    { id: 'lol_diamond3', name: 'Diamond III',  tier: 'Diamond',   division: 3, order: 25 },
    { id: 'lol_diamond2', name: 'Diamond II',   tier: 'Diamond',   division: 2, order: 26 },
    { id: 'lol_diamond1', name: 'Diamond I',    tier: 'Diamond',   division: 1, order: 27 },
    { id: 'lol_master',       name: 'Master',       tier: 'Master',       order: 28 },
    { id: 'lol_grandmaster',  name: 'Grandmaster',  tier: 'Grandmaster',  order: 29 },
    { id: 'lol_challenger',   name: 'Challenger',   tier: 'Challenger',   order: 30 },
  ],
};
