import { GameRankConfig } from '../types';

export const VALORANT_RANKS: GameRankConfig = {
  gameCode: 'VALORANT',
  gameName: 'Valorant',
  rankLabel: 'Rank',
  currency: 'USD',
  pricePerStep: 5.49,
  ranks: [
    { id: 'val_iron1',      name: 'Iron 1',      tier: 'Iron',      division: 1, order: 0 },
    { id: 'val_iron2',      name: 'Iron 2',      tier: 'Iron',      division: 2, order: 1 },
    { id: 'val_iron3',      name: 'Iron 3',      tier: 'Iron',      division: 3, order: 2 },
    { id: 'val_bronze1',    name: 'Bronze 1',    tier: 'Bronze',    division: 1, order: 3 },
    { id: 'val_bronze2',    name: 'Bronze 2',    tier: 'Bronze',    division: 2, order: 4 },
    { id: 'val_bronze3',    name: 'Bronze 3',    tier: 'Bronze',    division: 3, order: 5 },
    { id: 'val_silver1',    name: 'Silver 1',    tier: 'Silver',    division: 1, order: 6 },
    { id: 'val_silver2',    name: 'Silver 2',    tier: 'Silver',    division: 2, order: 7 },
    { id: 'val_silver3',    name: 'Silver 3',    tier: 'Silver',    division: 3, order: 8 },
    { id: 'val_gold1',      name: 'Gold 1',      tier: 'Gold',      division: 1, order: 9 },
    { id: 'val_gold2',      name: 'Gold 2',      tier: 'Gold',      division: 2, order: 10 },
    { id: 'val_gold3',      name: 'Gold 3',      tier: 'Gold',      division: 3, order: 11 },
    { id: 'val_plat1',      name: 'Platinum 1',  tier: 'Platinum',  division: 1, order: 12 },
    { id: 'val_plat2',      name: 'Platinum 2',  tier: 'Platinum',  division: 2, order: 13 },
    { id: 'val_plat3',      name: 'Platinum 3',  tier: 'Platinum',  division: 3, order: 14 },
    { id: 'val_diamond1',   name: 'Diamond 1',   tier: 'Diamond',   division: 1, order: 15 },
    { id: 'val_diamond2',   name: 'Diamond 2',   tier: 'Diamond',   division: 2, order: 16 },
    { id: 'val_diamond3',   name: 'Diamond 3',   tier: 'Diamond',   division: 3, order: 17 },
    { id: 'val_ascendant1', name: 'Ascendant 1', tier: 'Ascendant', division: 1, order: 18 },
    { id: 'val_ascendant2', name: 'Ascendant 2', tier: 'Ascendant', division: 2, order: 19 },
    { id: 'val_ascendant3', name: 'Ascendant 3', tier: 'Ascendant', division: 3, order: 20 },
    { id: 'val_immortal1',  name: 'Immortal 1',  tier: 'Immortal',  division: 1, order: 21 },
    { id: 'val_immortal2',  name: 'Immortal 2',  tier: 'Immortal',  division: 2, order: 22 },
    { id: 'val_immortal3',  name: 'Immortal 3',  tier: 'Immortal',  division: 3, order: 23 },
    { id: 'val_radiant',    name: 'Radiant',     tier: 'Radiant',               order: 24 },
  ],
};
